### ISSUE TITLE
Task 'event_events'  in the dag 'copy_deduplicate' failing due to table/view not found exception (telemetry.event))

### ISSUE THREAD

**Issue by kala725** [mozilla/telemetry-airflow#1171]
[2020-10-23 01:13:41,522] {logging_mixin.py:112} INFO - [2020-10-23 01:13:41,521] {pod_launcher.py:125} INFO - b'gcp:telemetry.event was not found in location US\n'
[2020-10-23 01:13:41,680] {logging_mixin.py:112} INFO - [2020-10-23 01:13:41,680] {pod_launcher.py:125} INFO - b'Traceback (most recent call last):\n'
[2020-10-23 01:13:41,681] {logging_mixin.py:112} INFO - [2020-10-23 01:13:41,681] {pod_launcher.py:125} INFO - b'  File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main\n'
[2020-10-23 01:13:41,681] {logging_mixin.py:112} INFO - [2020-10-23 01:13:41,681] {pod_launcher.py:125} INFO - b'    return _run_code(code, main_globals, None,\n'
[2020-10-23 01:13:41,681] {logging_mixin.py:112} INFO - [2020-10-23 01:13:41,681] {pod_launcher.py:125} INFO - b'  File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code\n'
[2020-10-23 01:13:41,681] {logging_mixin.py:112} INFO - [2020-10-23 01:13:41,681] {pod_launcher.py:125} INFO - b'    exec(code, run_globals)\n'
[2020-10-23 01:13:41,681] {logging_mixin.py:112} INFO - [2020-10-23 01:13:41,681] {pod_launcher.py:125} INFO - b'  File "/app/bigquery_etl/run_query.py", line 107, in <module>\n'
[2020-10-23 01:13:41,682] {logging_mixin.py:112} INFO - [2020-10-23 01:13:41,682] {pod_launcher.py:125} INFO - b'    main()\n'
[2020-10-23 01:13:41,682] {logging_mixin.py:112} INFO - [2020-10-23 01:13:41,682] {pod_launcher.py:125} INFO - b'  File "/app/bigquery_etl/run_query.py", line 97, in main\n'
[2020-10-23 01:13:41,682] {logging_mixin.py:112} INFO - [2020-10-23 01:13:41,682] {pod_launcher.py:125} INFO - b'    run(\n'
[2020-10-23 01:13:41,682] {logging_mixin.py:112} INFO - [2020-10-23 01:13:41,682] {pod_launcher.py:125} INFO - b'  File "/app/bigquery_etl/run_query.py", line 91, in run\n'
[2020-10-23 01:13:41,682] {logging_mixin.py:112} INFO - [2020-10-23 01:13:41,682] {pod_launcher.py:125} INFO - b'    subprocess.check_call(["bq"] + query_arguments, stdin=query_stream)\n'
[2020-10-23 01:13:41,682] {logging_mixin.py:112} INFO - [2020-10-23 01:13:41,682] {pod_launcher.py:125} INFO - b'  File "/usr/local/lib/python3.8/subprocess.py", line 364, in check_call\n'
[2020-10-23 01:13:41,682] {logging_mixin.py:112} INFO - [2020-10-23 01:13:41,682] {pod_launcher.py:125} INFO - b'    raise CalledProcessError(retcode, cmd)\n'
[2020-10-23 01:13:41,683] {logging_mixin.py:112} INFO - [2020-10-23 01:13:41,683] {pod_launcher.py:125} INFO - b"subprocess.CalledProcessError: Command '['bq', 'query', '--project_id=dataset', '--parameter=submission_date:DATE:2020-10-22', '--schema_update_option=ALLOW_FIELD_ADDITION', '--dataset_id=telemetry_derived', '--destination_table=event_events_v1$20201022']' returned non-zero exit status 2.\n"
[2020-10-23 01:13:42,732] {logging_mixin.py:112} INFO - [2020-10-23 01:13:42,731] {pod_launcher.py:142} INFO - Event: event-events-66c5f787 had an event of type Failed
[2020-10-23 01:13:42,783] {taskinstance.py:1145} ERROR - Pod Launching failed: Pod returned a failure: failed
Traceback (most recent call last):
  File "/app/dags/operators/backport/kubernetes_pod_operator_1_10_7.py", line 268, in execute
    'Pod returned a failure: {state}'.format(state=final_state)
airflow.exceptions.AirflowException: Pod returned a failure: failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 983, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/app/dags/operators/gcp_container_operator.py", line 98, in execute
    result = super(UpstreamGKEPodOperator, self).execute(context) # Moz specific
  File "/app/dags/operators/backport/kubernetes_pod_operator_1_10_7.py", line 273, in execute
    raise AirflowException('Pod Launching failed: {error}'.format(error=ex))
airflow.exceptions.AirflowException: Pod Launching failed: Pod returned a failure: failed
[2020-10-23 01:13:42,785] {taskinstance.py:1187} INFO - All retries failed; marking task as FAILED.dag_id=copy_deduplicate, task_id=event_events, execution_date=20201022T010000, start_date=20201023T011333, end_date=20201023T011342

**Comment by acmiyaguchi** [comment]
Hi, this is most likely because your GCP project does not contain the relevant resources required for the job to run successfully. You will have a bad experience running this project without the dataset/table combinations. I'm kind of curious what you were trying to do with `telemetry-airflow. Otherwise, I'm closing this issue because it works fine in our production instance.
